# Generated by Django 3.2.6 on 2021-08-19 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(default='', max_length=50, unique=True)),
                ('password', models.TextField(max_length=40)),
            ],
        ),
    ]
