# Generated by Django 3.2.6 on 2021-08-29 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='AIRRank',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='Aadhaar',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='student',
            name='AdmissionSource',
            field=models.CharField(default='JEE MAINS', max_length=15),
        ),
        migrations.AddField(
            model_name='student',
            name='AlternateContact',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='ApplicationNo',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='BloodGroup',
            field=models.CharField(default='', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='Branch',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='student',
            name='Category',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='student',
            name='CategoryRank',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='Contact',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='DateOfBirth',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='Email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='student',
            name='EnrollmentNumber',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='EntranceExam',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='student',
            name='FatherContact',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='student',
            name='FatherMail',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='student',
            name='Fathername',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='FeeWaiver',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='student',
            name='Gender',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='student',
            name='Hosteler',
            field=models.BooleanField(default='True'),
        ),
        migrations.AddField(
            model_name='student',
            name='IdentificationMark',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='student',
            name='ModeOfTransport',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='student',
            name='Mothername',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='Name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='Nationality',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='student',
            name='OfficialEmail',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='student',
            name='Programme',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='student',
            name='Religion',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='student',
            name='RollNo',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='student',
            name='SubCategory',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='student',
            name='YearOfEntranceExam',
            field=models.IntegerField(default=0),
        ),
    ]
