# Generated by Django 3.2.7 on 2021-09-22 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210829_1343'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoredSessions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default='', max_length=50, unique=True)),
                ('username', models.TextField(default='', max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='CGPA',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=7),
        ),
        migrations.AddField(
            model_name='student',
            name='CurrentSemester',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='student',
            name='photo',
            field=models.ImageField(default='', upload_to='api/images'),
        ),
    ]
