# Generated by Django 3.2.7 on 2021-10-25 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20211025_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='PasswordResetOTP',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
