# Generated by Django 3.2.7 on 2021-09-29 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210922_2324'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='encryptedpassword',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.TextField(max_length=40, null=True),
        ),
    ]
