# Generated by Django 3.2.7 on 2021-10-27 16:56

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_student_passwordresetotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Sign',
            field=models.ImageField(blank=True, default='sign.png', null=True, upload_to=""),
        ),
        migrations.AddField(
            model_name='student',
            name='Thumb',
            field=models.ImageField(blank=True, default='thumb.png', null=True, upload_to=""),
        ),
    ]
