# Generated by Django 3.2.7 on 2021-09-29 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210929_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='encryptedpassword',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
