# Generated by Django 3.2.7 on 2021-10-27 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20211027_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='PasswordResetting',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
