# Generated by Django 3.2.7 on 2021-10-10 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_student_encryptedpassword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='RollNo',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='encryptedpassword',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
