# Generated by Django 3.2.7 on 2021-10-27 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_student_passwordresetting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Photo',
            field=models.ImageField(blank=True, default='user.png', null=True, upload_to='images/studentPhoto'),
        ),
        migrations.AlterField(
            model_name='student',
            name='Sign',
            field=models.ImageField(blank=True, default='sign.png', null=True, upload_to='images/studentSign'),
        ),
        migrations.AlterField(
            model_name='student',
            name='Thumb',
            field=models.ImageField(blank=True, default='thumb.png', null=True, upload_to='images/studentThumb'),
        ),
    ]
