# Generated by Django 3.2.7 on 2021-11-14 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20211027_2348'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcelFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FileContent', models.FileField(upload_to='files/')),
                ('FileName', models.CharField(max_length=10, null=True, unique=True)),
            ],
        ),
    ]
