# Generated by Django 3.2.7 on 2021-10-11 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_student_rollno'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='Aadhaar',
            new_name='AadhaarCard',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='Fathername',
            new_name='FatherName',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='Email',
            new_name='HBTUEmail',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='Hosteler',
            new_name='Hostel',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='Mothername',
            new_name='MotherName',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='FatherMail',
            new_name='ParentEmail',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='OfficialEmail',
            new_name='PersonalEmail',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='RollNo',
            new_name='UniversityRollNo',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='YearOfEntranceExam',
            new_name='Year',
        ),
        migrations.RemoveField(
            model_name='student',
            name='Name',
        ),
        migrations.AddField(
            model_name='student',
            name='Landline',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='StudentName',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='StudentNameHindi',
            field=models.CharField(default='', max_length=50, null=True),
        ),
    ]
