# Generated by Django 3.2.7 on 2021-10-11 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20211011_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='SeatCategory',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='AIRRank',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='AadhaarCard',
            field=models.TextField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='AdmissionSource',
            field=models.CharField(default='JEE MAINS', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='AlternateContact',
            field=models.TextField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='ApplicationNo',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='Branch',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='CGPA',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='Category',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='CategoryRank',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='Contact',
            field=models.TextField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='CurrentSemester',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='EnrollmentNumber',
            field=models.CharField(default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='EntranceExam',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='FatherContact',
            field=models.TextField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='FatherName',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='FeeWaiver',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='Gender',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='HBTUEmail',
            field=models.EmailField(default='', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='Hostel',
            field=models.BooleanField(default='True', null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='IdentificationMark',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='ModeOfTransport',
            field=models.CharField(default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='MotherName',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='Nationality',
            field=models.CharField(default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='ParentEmail',
            field=models.EmailField(default='', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='PersonalEmail',
            field=models.EmailField(default='', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='Programme',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='Religion',
            field=models.CharField(default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='SubCategory',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='Year',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(default='', null=True, upload_to='api/images'),
        ),
    ]
