# Generated by Django 3.2.7 on 2021-10-11 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_student_studentnamehindi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='AIRRank',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='AadhaarCard',
            field=models.TextField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='AdmissionSource',
            field=models.CharField(blank=True, default='JEE MAINS', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='AlternateContact',
            field=models.TextField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='ApplicationNo',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='BloodGroup',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='Branch',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='CGPA',
            field=models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='Category',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='CategoryRank',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='Contact',
            field=models.TextField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='CurrentSemester',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='DateOfBirth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='EnrollmentNumber',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='EntranceExam',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='FatherContact',
            field=models.TextField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='FatherName',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='FeeWaiver',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='Gender',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='HBTUEmail',
            field=models.EmailField(blank=True, default='', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='Hostel',
            field=models.BooleanField(blank=True, default='True', null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='IdentificationMark',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='Landline',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='ModeOfTransport',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='MotherName',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='Nationality',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='ParentEmail',
            field=models.EmailField(blank=True, default='', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='PersonalEmail',
            field=models.EmailField(blank=True, default='', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='Programme',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='Religion',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='SubCategory',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='UniversityRollNo',
            field=models.TextField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='Year',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, default='', null=True, upload_to='api/images'),
        ),
    ]
