# Generated by Django 3.2.7 on 2021-11-14 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_syllabus_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syllabus',
            name='Branch',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
