# Generated by Django 3.2.7 on 2021-10-11 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20211011_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='SeatCategory',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
