# Generated by Django 3.2.7 on 2021-10-11 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_student_seatcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='BCABoard',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='BCADivision',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='BCAInstitution',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='BCARollNo',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='BCASubjects',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='BCAYear',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='BSCBoard',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='BSCDivision',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='BSCInstitution',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='BSCRollNo',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='BSCSubjects',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='BSCYear',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='BtechBoard',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='BtechDivision',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='BtechInstitution',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='BtechRollNo',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='BtechSubjcts',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='BtechYear',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='ChemMarks',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='CurAddress',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='CurAddress1',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='CurAddress2',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='CurCity',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='CurCountry',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='CurState',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='CurZipCode',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='HighSchoolBoard',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='HighSchoolDivision',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='HighSchoolInstitution',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='HighSchoolRollNo',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='HighSchoolSubjects',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='HighSchoolYear',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='IntermediateBoard',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='IntermediateDivision',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='IntermediateInstitution',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='IntermediateRollno',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='IntermediateYear',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='MCABoard',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='MCADivision',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='MCAInstitution',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='MCARollNo',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='MCASubjects',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='MCAYear',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='MSCBoard',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='MSCDivision',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='MSCInstitution',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='MSCRollNo',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='MSCSubjects',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='MSCYear',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='MathMarks',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='Member1Address',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='Member1Age',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='Member1EarningStatus',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='Member1EduQualification',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='Member1Income',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='Member1Name',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='Member1Occupation',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='Member1Organization',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='Member1ProQualification',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='Member1Relationship',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='Member2Address',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='Member2Age',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='Member2EarningStatus',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='Member2EduQualification',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='Member2Income',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='Member2Name',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='Member2Occupation',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='Member2Organization',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='Member2ProQualification',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='Member2Relationship',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='Member3Address',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='Member3Age',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='Member3EarningStatus',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='Member3EduQualification',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='Member3Income',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='Member3Name',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='Member3Occupation',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='Member3Organization',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='Member3ProQualification',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='Member3Relationship',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='Member4Address',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='Member4Age',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='Member4EarningStatus',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='Member4EduQualification',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='Member4Income',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='Member4Name',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='Member4Occupation',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='Member4Organization',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='Member4ProQualification',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='Member4Relationship',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='Member5Address',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='Member5Age',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='Member5EarningStatus',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='Member5EduQualification',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='Member5Income',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='Member5Name',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='Member5Occupation',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='Member5Organization',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='Member5ProQualification',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='Member5Relationship',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='MtechBoard',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='MtechDivision',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='MtechInstitution',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='MtechRollNo',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='MtechSubjects',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='MtechYear',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='PerAddress',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='PerAddress1',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='PerAddress2',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='PerCity',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='PerCountry',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='PerState',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='PerZipCode',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='Percentage',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='PhyMarks',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
