# Generated by Django 3.2.7 on 2021-11-21 13:58

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20211121_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='ResultSem1',
            field=models.FileField(blank=True, null=True, upload_to=api.models.upload_path_result),
        ),
        migrations.AlterField(
            model_name='student',
            name='ResultSem2',
            field=models.FileField(blank=True, null=True, upload_to=api.models.upload_path_result),
        ),
        migrations.AlterField(
            model_name='student',
            name='ResultSem3',
            field=models.FileField(blank=True, null=True, upload_to=api.models.upload_path_result),
        ),
        migrations.AlterField(
            model_name='student',
            name='ResultSem4',
            field=models.FileField(blank=True, null=True, upload_to=api.models.upload_path_result),
        ),
        migrations.AlterField(
            model_name='student',
            name='ResultSem5',
            field=models.FileField(blank=True, null=True, upload_to=api.models.upload_path_result),
        ),
        migrations.AlterField(
            model_name='student',
            name='ResultSem6',
            field=models.FileField(blank=True, null=True, upload_to=api.models.upload_path_result),
        ),
        migrations.AlterField(
            model_name='student',
            name='ResultSem7',
            field=models.FileField(blank=True, null=True, upload_to=api.models.upload_path_result),
        ),
        migrations.AlterField(
            model_name='student',
            name='ResultSem8',
            field=models.FileField(blank=True, null=True, upload_to=api.models.upload_path_result),
        ),
    ]
