# Generated by Django 3.2.7 on 2021-10-11 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20211011_1441'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='IntermediateRollno',
            new_name='IntermediateRollNo',
        ),
        migrations.AddField(
            model_name='student',
            name='IntermediateSubjects',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
