# Generated by Django 3.2.7 on 2021-10-11 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20211011_1443'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='BtechSubjcts',
            new_name='BtechSubjects',
        ),
    ]
