# Generated by Django 3.2.7 on 2021-10-11 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_rename_btechsubjcts_student_btechsubjects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='DateOfBirth',
            field=models.DateField(blank=True, default='', null=True),
        ),
    ]
