# Generated by Django 3.2.7 on 2021-10-11 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_student_dateofbirth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='StudentName',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
