# Generated by Django 3.2.7 on 2021-10-11 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_student_isformsaved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='IsformSaved',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
