# Generated by Django 3.2.7 on 2021-10-11 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_student_isformsaved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Hostel',
            field=models.TextField(blank=True, default='True', null=True),
        ),
    ]
