# Generated by Django 3.2.7 on 2021-10-16 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_auto_20211011_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='IsformSaved',
            field=models.TextField(blank=True, default='False', null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='IsformSubmitted',
            field=models.TextField(blank=True, default='False', null=True),
        ),
    ]
