# Generated by Django 3.1.4 on 2021-08-16 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.TextField(default='', max_length=50, unique=True)),
                ('password', models.IntegerField()),
            ],
        ),
    ]
