# Generated by Django 3.1.4 on 2021-08-16 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_student_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='name',
        ),
    ]
